services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./dockerfile
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      # 実行するコマンド。ここがすべて！
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  db-data:
